from flask import Flask, jsonify, request
from flask_cors import CORS


app = Flask(__name__)
CORS(app)


menu_items = [
    # {"id": 38, "name": "Minimum Scoop Chips", "category": "Deep Fried", "price": 4.50, "desc":"per scoop"},
    # {"id": 39, "name": "Kumara Chips", "category": "Deep Fried", "price": 9.00, "desc":"per scoop"},
    # {"id": 40, "name": "Potato Fritter", "category": "Deep Fried", "price": 1.50},
    # {"id": 41, "name": "Hash Brown", "category": "Deep Fried", "price": 1.90},
    # {"id": 42, "name": "Potato Balls", "category": "Deep Fried", "price": 3.60, "desc": "with Cheese & Onion"},
    # {"id": 43, "name": "Seasoned Potato Wedges", "category": "Deep Fried", "price": 6.50, "desc": "with Sour Cream"},
    # {"id": 44, "name": "Pineapple Fritter", "category": "Deep Fried", "price": 1.50, "desc": "with Cinnamon and Sugar"},
    # {"id": 45, "name": "Donuts", "category": "Deep Fried", "price": 1.40, "desc": "with Cinnamon and Sugar"},
    # {"id": 46, "name": "7 inch Battered Sausage", "category": "Deep Fried", "price": 3.80},
    # {"id": 47, "name": "Sausage Deep Fried", "category": "Deep Fried", "price": 2.00},
    # {"id": 48, "name": "Sausage Battered", "category": "Deep Fried", "price": 2.50},
    # {"id": 49, "name": "Kids Dog Battered on a Stick", "category": "Deep Fried", "price": 2.90},
    # {"id": 50, "name": "Mini Hot Dog", "category": "Deep Fried", "price": 1.40},
    # {"id": 51, "name": "Curry Roll", "category": "Deep Fried", "price": 3.20},
    # {"id": 52, "name": "Spring Roll", "category": "Deep Fried", "price": 3.20},
    # {"id": 53, "name": "American Hot Dog", "category": "Deep Fried", "price": 5.60, "desc": "with Onion, Cheese & Tomato Sauce"},
    # {"id": 54, "name": "Sea Dog", "category": "Deep Fried", "price": 5.50, "desc": "Crab Stick, Cheese & Tartare Sauce in Roll"},
    # {"id": 55, "name": "Chicken Schnitzel Crumbed", "category": "Deep Fried", "price": 5.50},
    # {"id": 56, "name": "Crab Stick Battered", "category": "Deep Fried", "price": 1.60},
    # {"id": 57, "name": "Fish of the Day", "category": "Deep Fried", "price": 5.00, "desc": "Battered or Crumbed ($1.40) with Tartare Sauce", "type": "fish"},
    # {"id": 58, "name": "Gurnard", "category": "Deep Fried", "price": 6.80, "desc": "Battered or Crumbed ($1.40) with Tartare Sauce", "type": "fish"},
    # {"id": 59, "name": "Tarakihi", "category": "Deep Fried", "price": 6.80, "desc": "Battered or Crumbed ($1.40) with Tartare Sauce", "type": "fish"},
    # {"id": 60, "name": "Snapper", "category": "Deep Fried", "price": 8.80, "desc": "Battered or Crumbed ($1.40) with Tartare Sauce", "type": "fish"},
    # {"id": 61, "name": "Fish Bites", "category": "Deep Fried", "price": 5.90, "desc": "6 Pieces with Tartare Sauce"},
    # {"id": 62, "name": "Mussel", "category": "Deep Fried", "price": 1.80, "desc": "Individual"},
    # {"id": 63, "name": "Mussels", "category": "Deep Fried", "price": 9.90, "desc": "6 Pack"},
    # {"id": 64, "name": "Scallop", "category": "Deep Fried", "price": 2.80, "desc": "Individual"},
    # {"id": 65, "name": "Scallops", "category": "Deep Fried", "price": 16.00, "desc": "6 Pack"},
    # {"id": 66, "name": "Oyster", "category": "Deep Fried", "price": 2.10, "desc": "Individual"},
    # {"id": 67, "name": "Oysters", "category": "Deep Fried", "price": 12.00, "desc": "6 Pack"},
    # {"id": 68, "name": "Squid Rings", "category": "Deep Fried", "price": 6.50, "desc": "6 Pack"},
    # {"id": 69, "name": "Onion Rings", "category": "Deep Fried", "price": 3.80, "desc": "6 Pack"},
    # {"id": 70, "name": "Chicken Nibbles Crumbed", "category": "Deep Fried", "price": 8.80, "desc": "6 Pack"},
    # {"id": 71, "name": "Chicken Nuggets", "category": "Deep Fried", "price": 5.90, "desc": "6 Pack"},
    # {"id": 72, "name": "Mini Spring Rolls", "category": "Deep Fried", "price": 4.20, "desc": "6 Pack"},
    # {"id": 73, "name": "Mini Samosas", "category": "Deep Fried", "price": 3.80, "desc": "6 Pack"},
    # {"id": 74, "name": "Fish Cake", "category": "Deep Fried", "price": 3.50},
    # {"id": 75, "name": "Mussel Fritter", "category": "Deep Fried", "price": 5.00},
    # {"id": 76, "name": "Paua Fritter", "category": "Deep Fried", "price": 5.00},
    # {"id": 77, "name": "Corn Fritter", "category": "Deep Fried", "price": 3.60},
    # {"id": 78, "name": "Deep Fried Mars Bar", "category": "Deep Fried", "price": 3.60},
    # {"id": 79, "name": "Banana Fritter", "category": "Deep Fried", "price": 2.80, "desc": "with Cinnamon and Sugar"},
    # {"id": 80, "name": "Wonton", "category": "Deep Fried", "price": 1.10, "desc": "Individual"},
    # {"id": 81, "name": "Wonton", "category": "Deep Fried", "price": 6.00, "desc": "6 Pack"},

    # {"id": 1, "name": "Plain Beef", "category": "Burgers", "price": 6.90, "subcategory": "Beef"},
    # {"id": 2, "name": "Beef Cheese", "category": "Burgers", "price": 7.90, "subcategory": "Beef"},
    # {"id": 3, "name": "Beef Cheese", "category": "Burgers", "price": 8.90, "desc": "with Bacon", "subcategory": "Beef"},
    # {"id": 4, "name": "Beef Cheese ", "category": "Burgers", "price": 10.20, "desc": "with Bacon & Egg", "subcategory": "Beef"},
    # {"id": 5, "name": "Beef Cheese", "category": "Burgers", "price": 12.80, "desc": "with Bacon, Egg & Avocado", "subcategory": "Beef"},
    # {"id": 6, "name": "Steak Egg & Cheese", "category": "Burgers", "price": 12.50, "subcategory": "Beef", "type": "no-desc"},
    # {"id": 7, "name": "Outback", "category": "Burgers", "price": 8.20, "desc": "Grill Cheese & Gherkins", "subcategory": "Beef", "type": "no-desc"},
    # {"id": 8, "name": "Southern", "category": "Burgers", "price": 9.30, "desc": "Cajun Spice with Cheese, Chilli Sauce & Sour Cream", "subcategory": "Beef", "type": "no-desc"},
    # {"id": 9, "name": "Mexican", "category": "Burgers", "price": 9.90, "desc": "Cheese, Jalapeno, Guacamole & Sour Cream", "subcategory": "Beef", "type": "no-desc"},
    # {"id": 10, "name": "Hawaiian", "category": "Burgers", "price": 9.90, "desc": "Bacon, Pineapple & Cheese", "subcategory": "Beef", "type": "no-desc"},
    # {"id": 11, "name": "Deluxe", "category": "Burgers", "price": 11.50, "desc": "Camembert & Bacon", "subcategory": "Beef", "type": "no-desc"},
    # {"id": 12, "name": "Texan", "category": "Burgers", "price": 12.80, "desc": "Steak, Mushrooms, BBQ Sauce & Sour Cream", "subcategory": "Beef", "type": "no-desc"},
    # {"id": 13, "name": "Legend", "category": "Burgers", "price": 13.50, "desc": "Avocado, Bacon & Camembert", "subcategory": "Beef", "type": "no-desc"},
    # {"id": 14, "name": "Ferga", "category": "Burgers", "price": 14.50, "desc": "Sliced beef, Cheese, Bacon, Avocado, Red Onion, Aioli & Tomato Relish", "subcategory": "Beef", "type": "no-desc"},
    # {"id": 15, "name": "Ferga Deluxe", "category": "Burgers", "price": 14.50, "desc": "Sliced beef, Bacon, Egg, Camembert, Aioli, Tomato Relish & Red Onion", "subcategory": "Beef", "type": "no-desc"},
    # {"id": 16, "name": "Gold Coast Beef", "category": "Burgers", "price": 13.90, "desc": "2 Patties, Bacon, Cheese & Egg ", "subcategory": "Beef", "type": "no-desc"},

    # {"id": 17, "name": "Plain Chicken", "category": "Burgers", "price": 6.90, "subcategory": "Chicken"},
    # {"id": 18, "name": "Chicken Cheese", "category": "Burgers", "price": 7.90, "subcategory": "Chicken"},
    # {"id": 19, "name": "Chicken Cheese", "category": "Burgers", "price": 8.90, "desc": "with Bacon", "subcategory": "Chicken"},
    # {"id": 20, "name": "Chicken Cheese", "category": "Burgers", "price": 12.50, "desc": "with Bacon & Avocado", "subcategory": "Chicken"},
    # {"id": 21, "name": "Kentucky", "category": "Burgers", "price": 9.30, "desc": "Cajun Spice with Cheese, Chilli Sauce & Sour Cream", "subcategory": "Chicken", "type": "no-desc"},
    # {"id": 22, "name": "Mexican", "category": "Burgers", "price": 9.90, "desc": "Cheese, Jalapeno, Guacamole & Sour Cream", "subcategory": "Chicken", "type": "no-desc"},
    # {"id": 23, "name": "Hawaiian", "category": "Burgers", "price": 9.90, "desc": "Bacon, Pineapple & Cheese", "subcategory": "Chicken", "type": "no-desc"},
    # {"id": 24, "name": "Deluxe", "category": "Burgers", "price": 11.50, "desc": "Camembert & Bacon", "subcategory": "Chicken", "type": "no-desc"},
    # {"id": 25, "name": "Supreme", "category": "Burgers", "price": 13.50, "desc": "Avocado, Bacon & Camembert", "subcategory": "Chicken", "type": "no-desc"},
    # {"id": 26, "name": "Gold Coast Chicken", "category": "Burgers", "price": 13.90, "desc": "Double Chicken with Bacon, Cheese & Egg ", "subcategory": "Chicken", "type": "no-desc"},

    # {"id": 27, "name": "Plain Beef", "category": "Burgers", "price": 5.80, "subcategory": "Junior"},
    # {"id": 28, "name": "Beef Cheese", "category": "Burgers", "price": 6.30, "subcategory": "Junior"},
    # {"id": 29, "name": "Beef Cheese", "category": "Burgers", "price": 7.80, "desc": "with Bacon", "subcategory": "Junior"},
    # {"id": 30, "name": "Beef Cheese", "category": "Burgers", "price": 8.90, "desc": "with Bacon & Egg", "subcategory": "Junior"},
    # {"id": 31, "name": "Plain Chicken", "category": "Burgers", "price": 5.80, "subcategory": "Junior"},
    # {"id": 32, "name": "Chicken Cheese", "category": "Burgers", "price": 6.30, "subcategory": "Junior"},
    # {"id": 33, "name": "Chicken Cheese", "category": "Burgers", "price": 7.80, "desc": "with Bacon", "subcategory": "Junior"},
    # {"id": 34, "name": "Chicken Cheese", "category": "Burgers", "price": 8.90, "desc": "with Bacon & Avocado", "subcategory": "Junior"},

    # {"id": 35, "name": "Fish Burger", "category": "Burgers", "price": 9.30, "desc": "Battered Fish & Cheese", "subcategory": "Other", "type": "no-desc"},
    # {"id": 36, "name": "Veggie Burger", "category": "Burgers", "price": 8.00, "desc":"Veggie Pattie & Cheese", "subcategory": "Other", "type": "no-desc"},
    # {"id": 37, "name": "Mexican Veggie Burger", "category": "Burgers", "price": 9.90, "desc":"Jalapenos, Avocado & Sour Cream", "subcategory": "Other", "type": "no-desc"},

    {"id": 1, "name": "Minimum Scoop Chips", "category": "Deep Fried", "price": 4.50, "desc":"per scoop"},
    {"id": 2, "name": "Kumara Chips", "category": "Deep Fried", "price": 9.00, "desc":"per scoop"},
    {"id": 3, "name": "Potato Fritter", "category": "Deep Fried", "price": 1.50},
    {"id": 4, "name": "Hash Brown", "category": "Deep Fried", "price": 1.90},
    {"id": 5, "name": "Potato Balls", "category": "Deep Fried", "price": 3.60, "desc": "with Cheese & Onion"},
    {"id": 6, "name": "Seasoned Potato Wedges", "category": "Deep Fried", "price": 6.50, "desc": "with Sour Cream"},
    {"id": 7, "name": "Pineapple Fritter", "category": "Deep Fried", "price": 1.50, "desc": "with Cinnamon and Sugar"},
    {"id": 8, "name": "Donuts", "category": "Deep Fried", "price": 1.40, "desc": "with Cinnamon and Sugar"},
    {"id": 9, "name": "7 inch Battered Sausage", "category": "Deep Fried", "price": 3.80},
    {"id": 10, "name": "Sausage Deep Fried", "category": "Deep Fried", "price": 2.00},
    {"id": 11, "name": "Sausage Battered", "category": "Deep Fried", "price": 2.50},
    {"id": 12, "name": "Kids Dog", "category": "Deep Fried", "price": 2.90, "desc": "Battered on a Stick"},
    {"id": 13, "name": "Mini Hot Dog", "category": "Deep Fried", "price": 1.40},
    {"id": 14, "name": "Curry Roll", "category": "Deep Fried", "price": 3.20},
    {"id": 15, "name": "Spring Roll", "category": "Deep Fried", "price": 3.20},
    {"id": 16, "name": "American Hot Dog", "category": "Deep Fried", "price": 5.60, "desc": "with Onion, Cheese & Tomato Sauce"},
    {"id": 17, "name": "Sea Dog", "category": "Deep Fried", "price": 5.50, "desc": "Crab Stick, Cheese & Tartare Sauce in Roll"},
    {"id": 18, "name": "Chicken Schnitzel Crumbed", "category": "Deep Fried", "price": 5.50},
    {"id": 19, "name": "Crab Stick Battered", "category": "Deep Fried", "price": 1.60},
    {"id": 20, "name": "Fish of the Day", "category": "Deep Fried", "price": 5.00, "desc": "Battered or Crumbed ($1.40) with Tartare Sauce", "type": "fish"},
    {"id": 21, "name": "Gurnard", "category": "Deep Fried", "price": 6.80, "desc": "Battered or Crumbed ($1.40) with Tartare Sauce", "type": "fish"},
    {"id": 22, "name": "Tarakihi", "category": "Deep Fried", "price": 6.80, "desc": "Battered or Crumbed ($1.40) with Tartare Sauce", "type": "fish"},
    {"id": 23, "name": "Snapper", "category": "Deep Fried", "price": 8.80, "desc": "Battered or Crumbed ($1.40) with Tartare Sauce", "type": "fish"},
    {"id": 24, "name": "Fish Bites", "category": "Deep Fried", "price": 5.90, "desc": "6 Pieces with Tartare Sauce"},
    {"id": 25, "name": "Mussel", "category": "Deep Fried", "price": 1.80, "desc": "Individual"},
    {"id": 26, "name": "Mussels", "category": "Deep Fried", "price": 9.90, "desc": "6 Pack"},
    {"id": 27, "name": "Scallop", "category": "Deep Fried", "price": 2.80, "desc": "Individual"},
    {"id": 28, "name": "Scallops", "category": "Deep Fried", "price": 16.00, "desc": "6 Pack"},
    {"id": 29, "name": "Oyster", "category": "Deep Fried", "price": 2.10, "desc": "Individual"},
    {"id": 30, "name": "Oysters", "category": "Deep Fried", "price": 12.00, "desc": "6 Pack"},
    {"id": 31, "name": "Squid Rings", "category": "Deep Fried", "price": 6.50, "desc": "6 Pack"},
    {"id": 32, "name": "Onion Rings", "category": "Deep Fried", "price": 3.80, "desc": "6 Pack"},
    {"id": 33, "name": "Chicken Nibbles Crumbed", "category": "Deep Fried", "price": 8.80, "desc": "6 Pack"},
    {"id": 34, "name": "Chicken Nuggets", "category": "Deep Fried", "price": 5.90, "desc": "6 Pack"},
    {"id": 35, "name": "Mini Spring Rolls", "category": "Deep Fried", "price": 4.20, "desc": "6 Pack"},
    {"id": 36, "name": "Mini Samosas", "category": "Deep Fried", "price": 3.80, "desc": "6 Pack"},
    {"id": 37, "name": "Fish Cake", "category": "Deep Fried", "price": 3.50},
    {"id": 38, "name": "Mussel Fritter", "category": "Deep Fried", "price": 5.00},
    {"id": 39, "name": "Paua Fritter", "category": "Deep Fried", "price": 5.00},
    {"id": 40, "name": "Corn Fritter", "category": "Deep Fried", "price": 3.60},
    {"id": 41, "name": "Deep Fried Mars Bar", "category": "Deep Fried", "price": 3.60},
    {"id": 42, "name": "Banana Fritter", "category": "Deep Fried", "price": 2.80, "desc": "with Cinnamon and Sugar"},
    {"id": 43, "name": "Wonton", "category": "Deep Fried", "price": 1.10, "desc": "Individual"},
    {"id": 44, "name": "Wonton", "category": "Deep Fried", "price": 6.00, "desc": "6 Pack"},
    {"id": 45, "name": "Plain Beef", "category": "Burgers", "price": 6.90, "subcategory": "Beef"},
    {"id": 46, "name": "Beef Cheese", "category": "Burgers", "price": 7.90, "subcategory": "Beef"},
    {"id": 47, "name": "Beef Cheese", "category": "Burgers", "price": 8.90, "desc": "with Bacon", "subcategory": "Beef"},
    {"id": 48, "name": "Beef Cheese ", "category": "Burgers", "price": 10.20, "desc": "with Bacon & Egg", "subcategory": "Beef"},
    {"id": 49, "name": "Beef Cheese", "category": "Burgers", "price": 12.80, "desc": "with Bacon, Egg & Avocado", "subcategory": "Beef"},
    {"id": 50, "name": "Steak Egg & Cheese", "category": "Burgers", "price": 12.50, "subcategory": "Beef", "type": "no-desc"},
    {"id": 51, "name": "Outback", "category": "Burgers", "price": 8.20, "desc": "Grill Cheese & Gherkins", "subcategory": "Beef", "type": "no-desc"},
    {"id": 52, "name": "Southern", "category": "Burgers", "price": 9.30, "desc": "Cajun Spice with Cheese, Chilli Sauce & Sour Cream", "subcategory": "Beef", "type": "no-desc"},
    {"id": 53, "name": "Mexican", "category": "Burgers", "price": 9.90, "desc": "Cheese, Jalapeno, Guacamole & Sour Cream", "subcategory": "Beef", "type": "no-desc"},
    {"id": 54, "name": "Hawaiian", "category": "Burgers", "price": 9.90, "desc": "Bacon, Pineapple & Cheese", "subcategory": "Beef", "type": "no-desc"},
    {"id": 55, "name": "Deluxe", "category": "Burgers", "price": 11.50, "desc": "Camembert & Bacon", "subcategory": "Beef", "type": "no-desc"},
    {"id": 56, "name": "Texan", "category": "Burgers", "price": 12.80, "desc": "Steak, Mushrooms, BBQ Sauce & Sour Cream", "subcategory": "Beef", "type": "no-desc"},
    {"id": 57, "name": "Legend", "category": "Burgers", "price": 13.50, "desc": "Avocado, Bacon & Camembert", "subcategory": "Beef", "type": "no-desc"},
    {"id": 58, "name": "Ferga", "category": "Burgers", "price": 14.50, "desc": "Sliced beef, Cheese, Bacon, Avocado, Red Onion, Aioli & Tomato Relish", "subcategory": "Beef", "type": "no-desc"},
    {"id": 59, "name": "Ferga Deluxe", "category": "Burgers", "price": 14.50, "desc": "Sliced beef, Bacon, Egg, Camembert, Aioli, Tomato Relish & Red Onion", "subcategory": "Beef", "type": "no-desc"},
    {"id": 60, "name": "Gold Coast Beef", "category": "Burgers", "price": 13.90, "desc": "2 Patties, Bacon, Cheese & Egg ", "subcategory": "Beef", "type": "no-desc"},
    {"id": 61, "name": "Plain Chicken", "category": "Burgers", "price": 6.90, "subcategory": "Chicken"},
    {"id": 62, "name": "Chicken Cheese", "category": "Burgers", "price": 7.90, "subcategory": "Chicken"},
    {"id": 63, "name": "Chicken Cheese", "category": "Burgers", "price": 8.90, "desc": "with Bacon", "subcategory": "Chicken"},
    {"id": 64, "name": "Chicken Cheese", "category": "Burgers", "price": 12.50, "desc": "with Bacon & Avocado", "subcategory": "Chicken"},
    {"id": 65, "name": "Kentucky", "category": "Burgers", "price": 9.30, "desc": "Cajun Spice with Cheese, Chilli Sauce & Sour Cream", "subcategory": "Chicken", "type": "no-desc"},
    {"id": 66, "name": "Mexican", "category": "Burgers", "price": 9.90, "desc": "Cheese, Jalapeno, Guacamole & Sour Cream", "subcategory": "Chicken", "type": "no-desc"},
    {"id": 67, "name": "Hawaiian", "category": "Burgers", "price": 9.90, "desc": "Bacon, Pineapple & Cheese", "subcategory": "Chicken", "type": "no-desc"},
    {"id": 68, "name": "Deluxe", "category": "Burgers", "price": 11.50, "desc": "Camembert & Bacon", "subcategory": "Chicken", "type": "no-desc"},
    {"id": 69, "name": "Supreme", "category": "Burgers", "price": 13.50, "desc": "Avocado, Bacon & Camembert", "subcategory": "Chicken", "type": "no-desc"},
    {"id": 70, "name": "Gold Coast Chicken", "category": "Burgers", "price": 13.90, "desc": "Double Chicken with Bacon, Cheese & Egg ", "subcategory": "Chicken", "type": "no-desc"},
    {"id": 71, "name": "Plain Beef", "category": "Burgers", "price": 5.80, "subcategory": "Junior"},
    {"id": 72, "name": "Beef Cheese", "category": "Burgers", "price": 6.30, "subcategory": "Junior"},
    {"id": 73, "name": "Beef Cheese", "category": "Burgers", "price": 7.80, "desc": "with Bacon", "subcategory": "Junior"},
    {"id": 74, "name": "Beef Cheese", "category": "Burgers", "price": 8.90, "desc": "with Bacon & Egg", "subcategory": "Junior"},
    {"id": 75, "name": "Plain Chicken", "category": "Burgers", "price": 5.80, "subcategory": "Junior"},
    {"id": 76, "name": "Chicken Cheese", "category": "Burgers", "price": 6.30, "subcategory": "Junior"},
    {"id": 77, "name": "Chicken Cheese", "category": "Burgers", "price": 7.80, "desc": "with Bacon", "subcategory": "Junior"},
    {"id": 78, "name": "Chicken Cheese", "category": "Burgers", "price": 8.90, "desc": "with Bacon & Avocado", "subcategory": "Junior"},
    {"id": 79, "name": "Fish Burger", "category": "Burgers", "price": 9.30, "desc": "Battered Fish & Cheese", "subcategory": "Other", "type": "no-desc"},
    {"id": 80, "name": "Veggie Burger", "category": "Burgers", "price": 8.00, "desc":"Veggie Pattie & Cheese", "subcategory": "Other", "type": "no-desc"},
    {"id": 81, "name": "Mexican Veggie Burger", "category": "Burgers", "price": 9.90, "desc":"Jalapenos, Avocado & Sour Cream", "subcategory": "Other", "type": "no-desc"},

    {"id": 82, "name": "Bacon, Lettuce & Tomato", "category": "Toasties", "price": 5.20},
    {"id": 83, "name": "Bacon, Egg & Cheese", "category": "Toasties", "price": 6.50},
    {"id": 84, "name": "Ham, Cheese & Tomato", "category": "Toasties", "price": 5.20},
    {"id": 85, "name": "Chicken, Avocado & Cheese", "category": "Toasties", "price": 8.00},

    {"id": 86, "name": "Milkshake", "category": "Drinks & Extras", "price": 6.00, "desc":"Banana, Caramel, Chocolate, Lime, Strawberry, Spearmint, Vanilla", "type": "shakes"},
    {"id": 87, "name": "Thickshake", "category": "Drinks & Extras", "price": 7.00, "desc":"Banana, Caramel, Chocolate, Lime, Strawberry, Spearmint, Vanilla", "type": "shakes"},
    {"id": 88, "name": "Can", "category": "Drinks & Extras", "price": 2.20, "desc": "Choice from a Variety of Soft Drinks"},
    {"id": 89, "name": "Bottle", "category": "Drinks & Extras", "price": 4.90, "desc": "Choice from a Variety of Soft Drinks"},
    {"id": 90, "name": "Wonton Soup", "category": "Drinks & Extras", "price": 15.50, "desc": "12 Pieces"},
    {"id": 91, "name": "Dumplings", "category": "Drinks & Extras", "price": 8.00, "desc": "6 Pack"},
    {"id": 92, "name": "Sweet & Sour Pork", "category": "Drinks & Extras", "price": "14.00 - $17.50"},
    {"id": 93, "name": "Sweet & Sour Pork", "category": "Hidden", "price": 17.50, "desc": "Large"},
    {"id": 94, "name": "Sweet & Sour Pork", "category": "Hidden", "price": 14.00, "desc": "Medium"},

    {"id": 95, "name": "Special A", "category": "Specials", "price": 9.00, "desc": ['1 Fish of the Day', '2 Potato Fritters', '$3 Chips']},
    {"id": 96, "name": "Special B", "category": "Specials", "price": 9.00, "desc": ['1 Sausage', '6 Chicken Nuggets', '$3 Chips']},
    {"id": 97, "name": "Special C", "category": "Specials", "price": 18.00, "desc": ['2 Fish of the Day', '2 Crab Sticks', '2 Sausages', '$3 Chips']},
    {"id": 98, "name": "Special D", "category": "Specials", "price": 19.00, "desc": ['2 Fish of the Day', '2 Potato Fritters', '4 Chicken Nuggets', '$3 Chips']},
    {"id": 99, "name": "Special E", "category": "Specials", "price": 36.00, "desc": ['4 Fish of the Day', '4 Sausages', '4 Potato Fritters', '$5 Chips']},
    {"id": 100, "name": "Special F", "category": "Specials", "price": 36.00, "desc": ['3 Fish of the Day', '3 Sausages', '3 Potato Balls', '3 Pineapple Fritters', '$4 Chips']},

    {"id": 101, "name": "Fish of the Day Crumbed", "price": 6.40, "category": "Hidden", "type": "crumb"},
    {"id": 102, "name": "Gurnard Crumbed", "price": 8.20, "category": "Hidden", "type": "crumb"},
    {"id": 103, "name": "Tarakihi Crumbed", "price": 8.20, "category": "Hidden", "type": "crumb"},
    {"id": 104, "name": "Snapper Crumbed", "price": 10.20, "category": "Hidden", "type": "crumb"}
]





@app.route('/api/menu', methods=['GET'])
def get_menu():
    return jsonify(menu_items)

if __name__ == '__main__':
    app.run(debug=True)
